# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('completed', '-date_updated')},
        ),
    ]
